# Application Name and Application specific configuration
[app."dnscrypt-proxy"]

# The path where the configuration files live.
# The purpose of this setting is to hide the path in the GUI
# Use absolute paths only
# Optional since the default is /var/packages/{PACKAGE NAME}/var/ for DSM7
# Optional since the default is /var/packages/{PACKAGE NAME}/target/var/ for DSM6
#directory = '/var/packages/dnscrypt-proxy/var/'

# List of configuration files
# The final file path is '/var/packages/' + directory + files[i]
files = [
    'dnscrypt-proxy.toml',
    'blocklist-names.txt',
    'blocklist-ips.txt',
    'cloaking-rules.txt',
    'forwarding-rules.txt',
    'allowed-names.txt',
    'allowed-ips.txt',
    'domains-blocklist.conf',
    'domains-time-restricted.txt',
    'domains-blocklist-local-additions.txt',
    'nx.log',
    'query.log'
]

# Applications can have one executable action
# Optionally the output of the command can be saved to a file
[app."dnscrypt-proxy".action]
    # Name of the button. I Recommend naming it with an action
    button_label = "Generate Blocklist"
    # Executable path
    exec = "python"
    # Arguments
    args = ["generate-domains-blocklist.py"]
    # Directory to change to before running the command
    # A file where the output is saved to. Must be a file from the previously set "files" option
    out-file = "blocklist.txt"
# [app."dnscrypt-proxy".action]
#     button_label = "Check config file"
#     exec = "/var/packages/dnscrypt-proxy/target/bin/dnscrypt-proxy"
#     args = ["-check", "-config", "/var/packages/dnscrypt-proxy/target/var/dnscrypt-proxy.toml"]

[app."wireguard"]
files = [
    'wg0.conf',
    'publickey'
]

###############################
#        SynoCommunity        #
###############################
[app."git"]
files = [
    "gitconfig"
]

[app."monit"]
files = [
    'monitrc',
    'monit.d/monit'
]

[app."sslh"]
files = [
    "sslh.cfg"
]

[app."syncthing"]
files = [
    "options.conf",
    "config.xml"
]

[app."i2pd"]
files = [
    "i2pd.conf"
]

##########################
#        Examples        #
##########################

# [app."example"]
# directory = '/var/packages/example/target/'
# files = [
#     'example.conf'
# ]

# [app."exampleAction".action]
#     button_label = "Get kernel name"
#     exec = "uname"

# [app."exampleAction2".action]
#     button_label = "List files"
#     dir = "/"
#     exec = "ls"
#     args = ["-l", "-a"]

#################################################################################
#       NOT TESTED! - Config files that I got from grepping synocommunity       #
#################################################################################

# [app."beets"]
# # DSM:
# directory = "/var/services/homes/your-user-name/.config/beets/config.yaml"
# files = [
#     "config.yaml"
# ]

# [app."haproxy"]
# files = [
#     "haproxy.cfg"
# ]

# [app."bitlbee"]
# files = [
#     "bitlbee.conf"
# ]

# [app."couchpotatoserver"]
# files = [
#     "settings.conf"
# ]

# [app."deluge"]
# files = [
#     "core.conf"
# ]

# [app."gateone"]
# files = [
#     "90custom.conf",
#     "95users.conf"
# ]

# [app."lirc"]
# files = [
#     "lircd.conf"
# ]

# [app."mosquitto"]
# files = [
#     "mosquitto.conf"
# ]

# [app."oscam"]
# files = [
#     "oscam.conf"
# ]

# [app."redis"]
# files = [
#     "redis.conf"
# ]

# [app."shairport-sync"]
# files = [
#     "alsa.conf"
# ]

# [app."squidguard"]
# files = [
#     "c-icap.conf",
#     "mime.conf",
#     "squid.conf",
#     "squidclamav.conf",
#     "squidguardmgr.conf",
# ]

# [app."umurmur"]
# files = [
#     "umurmur.conf"
# ]

# [app."znc"]
# files = [
#     "znc.conf"
# ]

# [app."flexget"]
# files = [
#     "config.yml"
# ]

# [app."wallabag"]
# files = [
#     "parameters.yml"
# ]

# [app."icecast"]
# files = [
#     "icecast.xml"
# ]

# [app."museek-plus"]
# files = [
#     "config.xml"
# ]

[app."radarr"]
files = [
    "config.xml"
]

[app."sonarr"]
files = [
    "config.xml"
]

[app."Transmission"]
files = [
    "settings.json",
    "transmission.log"
]
# [app."plexpy"]
# files = [
#     "config.ini"
# ]

# [app."headphones"]
# files = [
#     "config.ini"
# ]

# [app."sickrage"]
# files = [
#     "config.ini"
# ]

# [app."lazylibrarian"]
# files = [
#     "config.ini"
# ]

# [app."sabnzbd"]
# files = [
#     "config.ini"
# ]

# [app."comskip"]
# files = [
#     "config.ini"
# ]

# [app."mylar"]
# files = [
#     "config.ini"
# ]

# [app."plexivity"]
# files = [
#     "config.ini"
# ]

# [app."ffsync"]
# files = [
#     "ffsync.ini"
# ]
