[app."dnscrypt-proxy"]

# The path where the configuration files live
# root folder is '/var/packages/'
directory = 'dnscrypt-proxy/target/var/'

# List of configuration files
# The final file path is '/var/packages/' + directory + files[i]
files = [
    'dnscrypt-proxy.toml',
    'blacklist.txt',
    'ip-blacklist.txt',
    'cloaking-rules.txt',
    'forwarding-rules.txt',
    'whitelist.txt',
    'domains-blacklist.conf',
    'domains-whitelist.txt',
    'domains-time-restricted.txt',
    'domains-blacklist-local-additions.txt'
]

[app."dnscrypt-proxy".action]
    button_label = "Generate Blacklist"
    exec = "python"
    args = ["/var/packages/dnscrypt-proxy/target/var/generate-domains-blacklist.py"]
    dir = "/var/packages/dnscrypt-proxy/target/var"
    out-file = "/var/packages/dnscrypt-proxy/target/var/blacklist.txt"
# [app."dnscrypt-proxy".action]
#     button_label = "Check config file"
#     exec = "/var/packages/dnscrypt-proxy/target/bin/dnscrypt-proxy"
#     args = ["-check", "-config", "/var/packages/dnscrypt-proxy/target/var/dnscrypt-proxy.toml"]

[app."example"]
directory = 'example/target/var/'
files = [
    'example.toml'
]
