# Application Name and Application specific configuration
[app."dnscrypt-proxy"]

# The path where the configuration files live.
# The purpose of this setting is to hide the path in the GUI
# The root directory is '/var/packages/'
directory = 'dnscrypt-proxy/target/var/'

# List of configuration files
# The final file path is '/var/packages/' + directory + files[i]
files = [
    'dnscrypt-proxy.toml',
    'blacklist.txt',
    'ip-blacklist.txt',
    'cloaking-rules.txt',
    'forwarding-rules.txt',
    'whitelist.txt',
    'domains-blacklist.conf',
    'domains-whitelist.txt',
    'domains-time-restricted.txt',
    'domains-blacklist-local-additions.txt'
]

# Applications can have one executable action
# Optionally the output of the command can be saved to a file
[app."dnscrypt-proxy".action]
    # Name of the button. I Recommend naming it with an action
    button_label = "Generate Blacklist"
    # Executable path
    exec = "python"
    # Arguments
    args = ["/var/packages/dnscrypt-proxy/target/var/generate-domains-blacklist.py"]
    # Directory to change to before running the command
    dir = "/var/packages/dnscrypt-proxy/target/var"
    # A file where the output is saved to. Must be a file from the previously set "files" option
    out-file = "blacklist.txt"
# [app."dnscrypt-proxy".action]
#     button_label = "Check config file"
#     exec = "/var/packages/dnscrypt-proxy/target/bin/dnscrypt-proxy"
#     args = ["-check", "-config", "/var/packages/dnscrypt-proxy/target/var/dnscrypt-proxy.toml"]


####################################
#              Examples            #
####################################

# [app."example"]
# directory = 'example/target/'
# files = [
#     'example.conf'
# ]

# [app."exampleAction".action]
#     button_label = "Get kernel name"
#     exec = "uname"

# [app."exampleAction2".action]
#     button_label = "List files"
#     dir = "/"
#     exec = "ls"
#     args = ["-l", "-a"]
