[App."dnscrypt-proxy"]

# This field is deprecated in favour of the map[string]
name = 'dnscrypt-proxy'

# The path where the configuration files live
# root folder is '/var/packages/'
directory = 'dnscrypt-proxy/target/var/'

# List of configuration files
# The final file path is '/var/packages/' + directory + files[i]
files = [
    'dnscrypt-proxy.toml',
    'blacklist.txt',
    'ip-blacklist.txt',
    'cloaking-rules.txt',
    'forwarding-rules.txt',
    'whitelist.txt',
    'domains-blacklist.conf',
    'domains-whitelist.txt',
    'domains-time-restricted.txt',
    'domains-blacklist-local-additions.txt'
]
