# Application Name and Application specific configuration
[app."dnscrypt-proxy"]

# The path where the configuration files live.
# The purpose of this setting is to hide the path in the GUI
# Use absolute paths only
directory = '/var/packages/dnscrypt-proxy/target/var/'

# List of configuration files
# The final file path is '/var/packages/' + directory + files[i]
files = [
    'dnscrypt-proxy.toml',
    'blacklist.txt',
    'ip-blacklist.txt',
    'cloaking-rules.txt',
    'forwarding-rules.txt',
    'whitelist.txt',
    'domains-blacklist.conf',
    'domains-whitelist.txt',
    'domains-time-restricted.txt',
    'domains-blacklist-local-additions.txt'
]

# Applications can have one executable action
# Optionally the output of the command can be saved to a file
[app."dnscrypt-proxy".action]
    # Name of the button. I Recommend naming it with an action
    button_label = "Generate Blacklist"
    # Executable path
    exec = "python"
    # Arguments
    args = ["/var/packages/dnscrypt-proxy/target/var/generate-domains-blacklist.py"]
    # Directory to change to before running the command
    dir = "/var/packages/dnscrypt-proxy/target/var"
    # A file where the output is saved to. Must be a file from the previously set "files" option
    out-file = "blacklist.txt"
# [app."dnscrypt-proxy".action]
#     button_label = "Check config file"
#     exec = "/var/packages/dnscrypt-proxy/target/bin/dnscrypt-proxy"
#     args = ["-check", "-config", "/var/packages/dnscrypt-proxy/target/var/dnscrypt-proxy.toml"]

[app."wireguard"]
directory = '/var/packages/wireguard/target/var/'
files = [
    'wg0.conf',
    'publickey'
]

###############################
#        SynoCommunity        #
###############################
[app."git"]
directory = "/var/packages/git/target/var/"
files = [
    "gitconfig"
]

[app."monit"]
directory = '/var/packages/monit/target/var/'
files = [
    'monitrc',
    'monit.d/monit'
]

[app."sslh"]
directory = "/var/packages/sslh/target/var/"
files = [
    "sslh.cfg"
]

[app."syncthing"]
directory = "/var/packages/syncthing/target/var/"
files = [
    "options.conf",
    "config.xml"
]

[app."i2pd"]
directory = "/var/packages/i2pd/target/var/"
files = [
    "i2pd.conf"
]

##########################
#        Examples        #
##########################

# [app."example"]
# directory = '/var/packages/example/target/'
# files = [
#     'example.conf'
# ]

# [app."exampleAction".action]
#     button_label = "Get kernel name"
#     exec = "uname"

# [app."exampleAction2".action]
#     button_label = "List files"
#     dir = "/"
#     exec = "ls"
#     args = ["-l", "-a"]

#################################################################################
#       NOT TESTED! - Config files that I got from grepping synocommunity       #
#################################################################################

# [app."beets"]
# # DSM:
# directory = "/var/services/homes/your-user-name/.config/beets/config.yaml"
# files = [
#     "config.yaml"
# ]

# [app."haproxy"]
# directory = "/var/packages/haproxy/target/var/"
# files = [
#     "haproxy.cfg"
# ]

# [app."bitlbee"]
# directory = "/var/packages/bitlbee/target/var/"
# files = [
#     "bitlbee.conf"
# ]

# [app."couchpotatoserver"]
# directory = "/var/packages/couchpotatoserver/target/var/"
# files = [
#     "settings.conf"
# ]

# [app."deluge"]
# directory = "/var/packages/deluge/target/var/"
# files = [
#     "core.conf"
# ]

# [app."gateone"]
# directory = "/var/packages/gateone/target/var/"
# files = [
#     "90custom.conf",
#     "95users.conf"
# ]

# [app."lirc"]
# directory = "/var/packages/lirc/target/var/"
# files = [
#     "lircd.conf"
# ]

# [app."mosquitto"]
# directory = "/var/packages/mosquitto/target/var/"
# files = [
#     "mosquitto.conf"
# ]

# [app."oscam"]
# directory = "/var/packages/oscam/target/var/"
# files = [
#     "oscam.conf"
# ]

# [app."redis"]
# directory = "/var/packages/redis/target/var/"
# files = [
#     "redis.conf"
# ]

# [app."shairport-sync"]
# directory = "/var/packages/shairport-sync/target/var/"
# files = [
#     "alsa.conf"
# ]

# [app."squidguard"]
# directory = "/var/packages/squidguard/target/var/"
# files = [
#     "c-icap.conf",
#     "mime.conf",
#     "squid.conf",
#     "squidclamav.conf",
#     "squidguardmgr.conf",
# ]

# [app."umurmur"]
# directory = "/var/packages/umurmur/target/var/"
# files = [
#     "umurmur.conf"
# ]

# [app."znc"]
# directory = "/var/packages/znc/target/var/"
# files = [
#     "znc.conf"
# ]

# [app."flexget"]
# directory = "/var/packages/flexget/target/var/"
# files = [
#     "config.yml"
# ]

# [app."wallabag"]
# directory = "/var/packages/wallabag/target/var/"
# files = [
#     "parameters.yml"
# ]

# [app."icecast"]
# directory = "/var/packages/icecast/target/var/"
# files = [
#     "icecast.xml"
# ]

# [app."museek-plus"]
# directory = "/var/packages/museek-plus/target/var/"
# files = [
#     "config.xml"
# ]

# [app."radarr"]
# directory = "/var/packages/radarr/target/var/"
# files = [
#     "config.xml"
# ]

# [app."sonarr"]
# directory = "/var/packages/sonarr/target/var/"
# files = [
#     "config.xml"
# ]

# [app."plexpy"]
# directory = "/var/packages/plexpy/target/var/"
# files = [
#     "config.ini"
# ]

# [app."headphones"]
# directory = "/var/packages/headphones/target/var/"
# files = [
#     "config.ini"
# ]

# [app."sickrage"]
# directory = "/var/packages/sickrage/target/var/"
# files = [
#     "config.ini"
# ]

# [app."lazylibrarian"]
# directory = "/var/packages/lazylibrarian/target/var/"
# files = [
#     "config.ini"
# ]

# [app."sabnzbd"]
# directory = "/var/packages/sabnzbd/target/var/"
# files = [
#     "config.ini"
# ]

# [app."comskip"]
# directory = "/var/packages/comskip/target/var/"
# files = [
#     "config.ini"
# ]

# [app."mylar"]
# directory = "/var/packages/mylar/target/var/"
# files = [
#     "config.ini"
# ]

# [app."plexivity"]
# directory = "/var/packages/plexivity/target/var/"
# files = [
#     "config.ini"
# ]

# [app."ffsync"]
# directory = "/var/packages/ffsync/target/var/"
# files = [
#     "ffsync.ini"
# ]
