#!/bin/sh

case $1 in
    prestart)
        ;;
    prestop)
        ;;
    start)
        exit 0
        ;;
    stop)
        exit 0
        ;;
    status)
        exit 0
        ;;
    killall)
        ;;
    log)
        exit 0
        ;;
    *)
        exit 0
        ;;
esac
